version: '3'
networks:
  node_frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.13.1.0/24

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    networks:
      node_frontend:
        ipv4_address: 172.13.1.2
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    networks:
      node_frontend:
        ipv4_address: 172.13.1.3
    ports:
      - '27017:27017'
